[ERSSUP-61575]-[]-[Add base URL header]-[AP]
NHSDigital/e-referrals-service-patient-care-api pull request #18
Opened 2022-04-28 08:25 UTC by nhsd-angel-pastor

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2022-05-03 16:06 UTC, nhsd-angel-pastor commented on proxies/live/apiproxy/policies/AssignMessage.AddBaseUrlHeader.xml
> +            <Header name="x-ers-network-baseurl">https://{request.header.Host}/{proxy.basepath}</Header>
make it nhsd-ers-network-baseurl

2022-05-03 16:23 UTC, nhsd-angel-pastor commented on proxies/live/apiproxy/policies/AssignMessage.RemoveAndAddApplicationIdHeader.xml
> +      <Header name="x-application-id">{developer.app.id}</Header>
nhsd-application-id

2022-05-03 16:23 UTC, nhsd-angel-pastor commented on proxies/live/apiproxy/policies/AssignMessage.RemoveAndAddApplicationIdHeader.xml
> +      <Header name="x-application-id">{developer.app.id}</Header>
use <Set> instead of Remove & Add

2022-05-03 16:27 UTC, nhsd-angel-pastor commented on proxies/live/apiproxy/policies/AssignMessage.RemoveAndAddNhsNumberHeader.xml
> +      <Header name="NHSD-Nhs-Number"/>
nhsd-nhs-number

2022-05-03 16:37 UTC, nhsd-angel-pastor commented on proxies/live/apiproxy/policies/AssignMessage.Swap.TransactionID.xml
> +      <Header name="X-Request-ID">{message.header.X_ERS_TRANSACTION_ID}</Header>
nhsd-ers-transaction-id

2022-05-03 16:40 UTC, nhsd-angel-pastor commented on proxies/live/apiproxy/policies/AssignMessage.Swap.TransactionID.xml
> +      <Header name="X_ERS_TRANSACTION_ID"/>
change to nhsd-ers-transaction-id

2022-05-03 16:46 UTC, nhsd-angel-pastor commented on proxies/live/apiproxy/policies/AssignMessage.Swap.CorrelationHeader.xml
> +      <Header name="NHSD-Correlation-ID">{message.header.X-Correlation-ID}.{messageid}</Header>
nhsd-correlation-id

2022-05-03 16:55 UTC, nhsd-angel-pastor commented on proxies/live/apiproxy/policies/AssignMessage.RemoveAndAddAccessTokenHeader.xml
> +      <Header name="NHSD-Access-Token"/>
casing

2022-05-04 09:55 UTC, adamoldfield-nhs requested changes
Looks good just a couple of questions.

2022-05-04 09:55 UTC, adamoldfield-nhs commented on proxies/live/apiproxy/policies/AssignMessage.Swap.CorrelationHeader.xml
> +      <Header name="nhsd-correlation-id">{message.header.X-Correlation-ID}.{messageid}</Header>
Should the property be lower case too? Also the header in the remove section below?

It shouldn't make a difference but I guess we should be consistent?

2022-05-04 09:55 UTC, adamoldfield-nhs commented on proxies/live/apiproxy/policies/AssignMessage.Swap.TransactionID.xml
> +      <Header name="X-Request-ID">{message.header.nhsd-ers-transaction-id}</Header>
I think this should be lowercase too?

2022-05-04 14:19 UTC, merged